"""initial schema

Revision ID: 4992d1a4ec63
Revises:
Create Date: 2026-08-23 03:54:12.211716

Hand-written from app/db/postgres_models.py rather than autogenerated: no
Postgres instance was available to run `alembic revision --autogenerate`
against at the time this was created. Every table/column/index below was
verified by compiling `CreateTable`/`CreateIndex` for each model against the
postgresql dialect and diffing the output against this file — see the PR/
commit description for that verification output.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4992d1a4ec63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "ai_summaries",
        sa.Column("appointment_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("appointment_id", "kind"),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "calendar_connections",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expiry", sa.String(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )

    op.create_table(
        "clinical_notes",
        sa.Column("appointment_id", sa.String(), nullable=False),
        sa.Column("doctor_id", sa.String(), nullable=False),
        sa.Column("clinical_notes", sa.Text(), nullable=False),
        sa.Column("diagnosis", sa.String(), nullable=False),
        sa.Column("medications", sa.JSON(), nullable=True),
        sa.Column("follow_up_instructions", sa.Text(), nullable=True),
        sa.Column("follow_up_date", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("appointment_id"),
    )

    op.create_table(
        "medication_reminders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("appointment_id", sa.String(), nullable=False),
        sa.Column("medicine_name", sa.String(), nullable=False),
        sa.Column("dosage", sa.String(), nullable=False),
        sa.Column("instructions", sa.String(), nullable=True),
        sa.Column("scheduled_at", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medication_reminders_scheduled_at"), "medication_reminders", ["scheduled_at"])
    op.create_index(op.f("ix_medication_reminders_patient_id"), "medication_reminders", ["patient_id"])
    op.create_index(op.f("ix_medication_reminders_status"), "medication_reminders", ["status"])
    op.create_index(op.f("ix_medication_reminders_appointment_id"), "medication_reminders", ["appointment_id"])

    op.create_table(
        "notifications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("to_email", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("sent_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_status"), "notifications", ["status"])
    op.create_index(op.f("ix_notifications_next_retry_at"), "notifications", ["next_retry_at"])

    op.create_table(
        "slot_holds",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("doctor_id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("start", sa.String(), nullable=False),
        sa.Column("end", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_slot_holds_start"), "slot_holds", ["start"])
    op.create_index(op.f("ix_slot_holds_status"), "slot_holds", ["status"])
    op.create_index(op.f("ix_slot_holds_expires_at"), "slot_holds", ["expires_at"])
    op.create_index(op.f("ix_slot_holds_patient_id"), "slot_holds", ["patient_id"])
    op.create_index(op.f("ix_slot_holds_doctor_id"), "slot_holds", ["doctor_id"])

    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("specialization", sa.String(), nullable=True),
        sa.Column("qualification", sa.String(), nullable=True),
        sa.Column("experience", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("work_start", sa.String(), nullable=False),
        sa.Column("work_end", sa.String(), nullable=False),
        sa.Column("slot_duration", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "waitlist",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("doctor_id", sa.String(), nullable=False),
        sa.Column("requested_start", sa.String(), nullable=False),
        sa.Column("requested_end", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("claim_expires_at", sa.String(), nullable=True),
        sa.Column("appointment_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_active_waitlist",
        "waitlist",
        ["patient_id", "doctor_id", "requested_start"],
        unique=True,
        postgresql_where=sa.text("status IN ('WAITING','NOTIFIED')"),
    )
    op.create_index(op.f("ix_waitlist_requested_start"), "waitlist", ["requested_start"])
    op.create_index(op.f("ix_waitlist_doctor_id"), "waitlist", ["doctor_id"])
    op.create_index(op.f("ix_waitlist_patient_id"), "waitlist", ["patient_id"])
    op.create_index(op.f("ix_waitlist_status"), "waitlist", ["status"])

    op.create_table(
        "appointments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("doctor_id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("start", sa.String(), nullable=False),
        sa.Column("end", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("symptoms", sa.JSON(), nullable=True),
        sa.Column("ai_status", sa.String(), nullable=False),
        sa.Column("post_ai_status", sa.String(), nullable=True),
        sa.Column("notification_status", sa.String(), nullable=False),
        sa.Column("calendar_status", sa.String(), nullable=False),
        sa.Column("clinical_status", sa.String(), nullable=True),
        sa.Column("cancellation_reason", sa.String(), nullable=True),
        sa.Column("patient_event_id", sa.String(), nullable=True),
        sa.Column("doctor_event_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["doctor_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["patient_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_active_appt",
        "appointments",
        ["doctor_id", "start"],
        unique=True,
        postgresql_where=sa.text("status IN ('HELD','CONFIRMED')"),
    )
    op.create_index(op.f("ix_appointments_start"), "appointments", ["start"])
    op.create_index(op.f("ix_appointments_patient_id"), "appointments", ["patient_id"])
    op.create_index(op.f("ix_appointments_doctor_id"), "appointments", ["doctor_id"])
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"])

    op.create_table(
        "doctor_leaves",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doctor_id", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["doctor_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doctor_id", "date", name="uq_doctor_date"),
    )
    op.create_index(op.f("ix_doctor_leaves_doctor_id"), "doctor_leaves", ["doctor_id"])
    op.create_index(op.f("ix_doctor_leaves_date"), "doctor_leaves", ["date"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("doctor_leaves")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_doctor_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_start"), table_name="appointments")
    op.drop_index("uq_active_appt", table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_waitlist_status"), table_name="waitlist")
    op.drop_index(op.f("ix_waitlist_patient_id"), table_name="waitlist")
    op.drop_index(op.f("ix_waitlist_doctor_id"), table_name="waitlist")
    op.drop_index(op.f("ix_waitlist_requested_start"), table_name="waitlist")
    op.drop_index("uq_active_waitlist", table_name="waitlist")
    op.drop_table("waitlist")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_slot_holds_doctor_id"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_patient_id"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_expires_at"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_status"), table_name="slot_holds")
    op.drop_index(op.f("ix_slot_holds_start"), table_name="slot_holds")
    op.drop_table("slot_holds")
    op.drop_index(op.f("ix_notifications_next_retry_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_medication_reminders_appointment_id"), table_name="medication_reminders")
    op.drop_index(op.f("ix_medication_reminders_status"), table_name="medication_reminders")
    op.drop_index(op.f("ix_medication_reminders_patient_id"), table_name="medication_reminders")
    op.drop_index(op.f("ix_medication_reminders_scheduled_at"), table_name="medication_reminders")
    op.drop_table("medication_reminders")
    op.drop_table("clinical_notes")
    op.drop_table("calendar_connections")
    op.drop_table("audit_logs")
    op.drop_table("ai_summaries")
